export const MILLISECONDS_IN_SECOND = 1000;

export const SECONDS_IN_MINUTE = 60;
export const MILLISECONDS_IN_MINUTE = SECONDS_IN_MINUTE * MILLISECONDS_IN_SECOND;

export const MINUTES_IN_HOUR = 60;
export const MILLISECONDS_IN_HOUR = MINUTES_IN_HOUR * MILLISECONDS_IN_MINUTE;

export const HOURS_IN_DAY = 24;
export const MILLISECONDS_IN_DAY = HOURS_IN_DAY * MILLISECONDS_IN_HOUR;

export const DAYS_IN_WEEK = 7;
export const MILLISECONDS_IN_WEEK = DAYS_IN_WEEK * MILLISECONDS_IN_DAY;

export const DAYS_IN_YEAR = 365;
export const MILLISECONDS_IN_YEAR = DAYS_IN_YEAR * MILLISECONDS_IN_DAY;


// app constants
export const DEFAULT_AUTH_DAYS_VALID = 30;
export const DEFAULT_AUTH_TIME_VALID = DEFAULT_AUTH_DAYS_VALID * MILLISECONDS_IN_DAY;
